### ISSUE TITLE
Remove `n_luh_states` from EDInitMod.F90?

### ISSUE THREAD

**Issue by glemieux** [ckoven/fates#16]
Since we have `hlm_num_luh2_states`, can we remove the block that counts up the number of states into the (as yet) unused variable `n_luh_states` found in `init_patches`?

https://github.com/ckoven/fates/blob/44696201f9dd9a3add7889f805d39ef82b7205ff/main/EDInitMod.F90#L594-L612

**Comment by ckoven** [comment]
The intention was for `n_luh_states` to be the number of nonzero states, but since we aren't using it yet we can just remove it entirely.  All we should need from this block is the call to get the `state_vector`

**Comment by glemieux** [comment]
Roger that.  So the intent is to create new patches downstream of that code with areas for the specific land use type based on the `state_vector` values, correct?

https://github.com/ckoven/fates/blob/44696201f9dd9a3add7889f805d39ef82b7205ff/main/EDInitMod.F90#L642-L644

**Comment by ckoven** [comment]
right.
